//abstract method
public class blackBox extends LoadRunner{


	public static void main(String[] args) {
		// TODO Auto-generated method stub
	LoadRunner load=new blackBox();
	load.testcases();
	load=new Selenium();
	load.testcases();


	}
	@Override
	public void testcases()
	{
		System.out.println("generated by user as well as automatic");
	}
}
	class Selenium extends LoadRunner
	{
		@Override
		public void testcases()
		{
			System.out.println("Selenium auto");
		}
		
	}
	
abstract class LoadRunner{
	public void test(){System.out.println(";Load capacity of iste");}
	abstract public void testcases();
}


